#!/usr/bin/env python3
# @pas-executable
# Merge mp3s by inserting silence between them.
"""
"""

import os, sys, subprocess, shutil

selected_folder = sys.argv[1]
# Silence file path - should be provided by user or exist in a standard location
silence = os.environ.get('PAS_SILENCE_MP3', os.path.expanduser('~/bin/s.mp3'))
mp3s = []

log_file_n = os.path.join(selected_folder,'merge.log')
with open(log_file_n, 'w') as log:
	log.write('selected folder: %s\n' % selected_folder)
	basefn = os.path.basename(selected_folder)
	mp3_out = basefn + '.mp3'
	log.write('output mp3 file: %s\n' %  mp3_out)
	for root, subFolders, files in os.walk(selected_folder):
		mp3s = [i for i in files if i.endswith('.mp3')]
		log.write('root: %s\n' % root)
		log.write('source mp3 files: %s\n' % mp3s)
	
	sox_path = shutil.which('sox') or 'sox'
	cmd = '%s %s ../../%s' % (sox_path, (' %s ' % silence).join(mp3s), mp3_out)
	log.write('cmd: %s\n' % cmd)
	os.chdir(selected_folder)
	subprocess.call(cmd, shell=True)
	cmd = 'cd ../; mv %s _%s' % (basefn, basefn)
	log.write('cmd: %s\n' % cmd)
	subprocess.call(cmd, shell=True)
    

