#!/usr/bin/env python3
# @pas-executable
"""
Having a series of .mp3 files, split the 1st mp3 into 2 parts at default 1.5 secs.
Use the 1st part as one file, and then merge the 2nd part with other mp3s.
"""

import sys, subprocess, shutil
f_split = sys.argv[1]
f_other = sys.argv[2:] # the last one is output file

soxi_path = shutil.which('soxi') or 'soxi'
mp3splt_path = shutil.which('mp3splt') or 'mp3splt'

def t_convert(s):
    return '.'.join(s.split(':')[1:])

cmd = '%s -d %s' % (soxi_path, f_split)
p = subprocess.Popen(cmd, stdout=subprocess.PIPE, shell=True)
audio_duration = t_convert(p.communicate()[0].strip().decode('utf-8'))

cmd = '%s -o @f_@n 00.00.00 00.01.50 %s %s' % (mp3splt_path, audio_duration, f_split)
print(cmd)
subprocess.call(cmd, shell=True)

cmd = 'mv %s %s' % (f_split, '_del')
print(cmd)
subprocess.call(cmd, shell=True)

cmd = 'mp3pad_n_merge %s %s' % ('1_2.mp3', ' '.join(f_other))
print(cmd)
subprocess.call(cmd, shell=True)

